### ISSUE TITLE
Error importing iChorCNA WDL script into DNAnexus

### ISSUE THREAD

**Issue by ninaxiong11** [broadinstitute/TAG-public#36]
When I try to import iChorCNA_hg38.wdl into DNAnexus, I get the following error:

"WDL code is syntactically valid BUT it fails type-checking"

How can I fix this issue? Thank you!

**Comment by yueyaog** [comment]
Hi! Our team use WDLs in this repo internally on the Terra platform, and our support is currently limited to users utilizing these workflows within the Terra platform. Unfortunately, we are unable to provide assistance for users attempting to run the WDLs elsewhere, such as in DNAnexus.
