### ISSUE TITLE
CODEC Duplexes end trimming

### ISSUE THREAD

**Issue by AzeetN** [broadinstitute/TAG-public#71]
End repair of DNA templates  using ddBTP and duplex repair (DrV1 and DrV2) limits the re-synthesis of strands, should we remove the 12 base pair trimming step in CODEC analysis pipeline?

**Comment by stellaning1120** [comment]
Closing this because we have a ticket open and discussed in TAG repo:
https://github.com/broadinstitute/TAG/issues/2114
