### ISSUE TITLE
GATK4 CNV + Mutect2 analysis request 

### ISSUE THREAD

**Issue by Akluge01** [broadinstitute/TAG-public#8]
Good morning TAG team,

I'd like to request the standard GATK4 CNV + Mutect2 analysis (P-ANA-0039) on a tumor/normal pair that was sequenced on the targeted cancer panel at 250xMTC in PDO-29201 (https://labopsjira.broadinstitute.org/browse/PDO-29201). 

I am also requesting the same pipeline in tumor-only mode on the tumor-only sample (P-ANA-0038). Per Carrie Cibulskis's recommendation, we would like to include the exome PoN as the panel of normals and understand the caveats associated with doing this. 

I have attached a list of SM-IDs for your reference and Carrie indicated that GP will cover the cost of analysis for the samples. 

Please let me know if there are any questions or concerns with this request and thank you in advance for your assistance! 
[TAG analysis samples   .xlsx](https://github.com/broadinstitute/TAG-public/files/10481462/TAG.analysis.samples.xlsx)

**Comment by fleharty** [comment]
@Akluge01 This repository is not used for TAG analysis.
I've recreated your ticket in the proper repository and tagged you there.
